### ISSUE TITLE
proposal: change to `predRest` instead of `predElse`

### ISSUE THREAD

**Issue by Milly** [jsr-core/unknownutil#114]
`isTupleOf` and `isParametersOf` have an argument `predElse`, but I propose to change this to `predRest`.
These are called rest-elements and rest-parameters, so wouldn't `rest` be better than `else`?

**Comment by lambdalisue** [comment]
Agreed.

:memo:

mdn use a term "rest parameters"
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

**Comment by Milly** [comment]
Typescript use a term "rest parameters" for function parameters, and "rest elements" for tuple types.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#rest-elements-in-tuple-types
