### ISSUE TITLE
feat: add predicate functions of basic types like `Promise`, `Date`, `Iterable`, etc.

### ISSUE THREAD

**Issue by lambdalisue** [jsr-core/unknownutil#118]
We can use `isInstanceOf` or `isObjectOf` now but for convinience.

- [ ] `Promise`
- [ ] `Date`
- [ ] `Temporal`
- [ ] `Worker`
- [ ] `Iterable`
- [ ] `AsyncIterable`
- [ ] `Disposable`
- [ ] `AsyncDisposable`
- etc.

**Comment by Milly** [comment]
```ts
type Jsonable = {
  /**
   * Returns a JSON value that can be specified to {@linkcode JSON.stringify}.
   *
   * @see {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior|toJSON() behavior}
   */
  toJSON(key: string | number): unknown;
};

function isJsonable(x: unknown): x is Jsonable {
  return x != null && isFunction((x as Jsonable).toJSON);
}
```

💭 I wonder if we define this in unknownutil.

_Originally posted by @lambdalisue in https://github.com/vim-denops/deno-denops-std/pull/260#discussion_r1717938943_

**Comment by Milly** [comment]
```ts
const isInstanceOfBoolean = isInstanceOf(Boolean);
const isInstanceOfNumber = isInstanceOf(Number);
const isInstanceOfString = isInstanceOf(String);
```

💭 I wonder if we define these in unknownutil like `isBooleanInstance`, etc.

_Originally posted by @lambdalisue in https://github.com/vim-denops/deno-denops-std/pull/260#discussion_r1717941033_

**Comment by lambdalisue** [comment]
> ```ts
> 
> type Jsonable = {
> 
>   /**
> 
>    * Returns a JSON value that can be specified to {@linkcode JSON.stringify}.
> 
>    *
> 
>    * @see {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior|toJSON() behavior}
> 
>    */
> 
>   toJSON(key: string | number): unknown;
> 
> };
> 
> 
> 
> function isJsonable(x: unknown): x is Jsonable {
> 
>   return x != null && isFunction((x as Jsonable).toJSON);
> 
> }
> 
> ```
> 
> 
> 
> 💭 I wonder if we define this in unknownutil.
> 
> 
> 
> _Originally posted by @lambdalisue in https://github.com/vim-denops/deno-denops-std/pull/260#discussion_r1717938943_

I think null is jsonable

**Comment by Milly** [comment]
> I think null is jsonable

Discussion and implementation of `isJsonable` in #128.

**Comment by lambdalisue** [comment]
I changed my mind. It's impossible to define "what is the bacis types".
