### ISSUE TITLE
When importing like `import { is } from "@core/unknownutil";` on Node, all `is~` functions are `any`

### ISSUE THREAD

**Issue by ryoppippi** [jsr-core/unknownutil#86]
Here is  the reproduce steps:
```sh
mkdir ex && cd ex
bun init -y # bun creates tsconfig.json, so I use this
npm i # install with node 
npx jsr add @core/unknownutil@3.18.1

# or
# bun i
# bunx jsr add @core/unknownutil@3.18.1
```
Then, Open `index.ts` and write `import` statement.
And you can see all methods are `any`

![Screenshot 2024-06-21 at 00 01 14](https://github.com/jsr-core/unknownutil/assets/1560508/de7e56ba-baf5-47b6-9c9d-6e6754bf4b7d)

However, if you use named import, it works
![Screenshot 2024-06-21 at 00 02 08](https://github.com/jsr-core/unknownutil/assets/1560508/3b9d9076-6542-4c2c-9d14-ae4eb5ae5311)

This is my environmental information:
```
/t/example 3m 45.9s ❱ node --version
v22.0.0
/t/example ❱ uname -mprs
Darwin 23.5.0 arm64 arm
```

I checked with 
- `vtsls` + `nvim-lspconfig`
- the latest VSCode

but the results are same.

**Comment by lambdalisue** [comment]
I'm not sure but maybe JSR's issue or we may need some extra things for types on npm with JSR?

**Comment by lambdalisue** [comment]
https://github.com/jsr-io/jsr/issues/615

Closed via that
