### ISSUE TITLE
doc: Collection objects has no property documents

### ISSUE THREAD

**Issue by Milly** [jsr-core/unknownutil#90]
## Problem

These collection objects has no property documents.
- [as](https://jsr.io/@core/unknownutil@4.0.1/doc/~/as)
- [is](https://jsr.io/@core/unknownutil@4.0.1/doc/~/is)

## Expected

Add documents.

## Additional

Tried to fix in #89, but closed.

**Comment by lambdalisue** [comment]
I talked with Deno's member (@kt3k). He said that we need to do Copy & Paste the docs at least for now.

https://github.com/denoland/deno_doc/issues/140

**Comment by Milly** [comment]
I think it would be better to implement auto-generation.

**Comment by lambdalisue** [comment]
Yes. I was wondering that as well.

**Comment by lambdalisue** [comment]
https://github.com/jsr-core/unknownutil/pull/106#issuecomment-2276422845

**Comment by lambdalisue** [comment]
The 2nd one works like a charm 🎉 

![CleanShot 2024-08-09 at 11 26 33](https://github.com/user-attachments/assets/5556bcc4-66cb-4dad-b53a-e4cce2ec8b8b)
