### ISSUE TITLE
question: `isObjectOf()` intended to check prototype properties?

### ISSUE THREAD

**Issue by Milly** [jsr-core/unknownutil#92]
## Question

`isObjectOf()` checks prototype properties. This is intended?

```typescript
const parent = { a: is.Number };
const child = Object.create(parent);
child.b = is.String;

is.ObjectOf(child)({ a: 0 }); // false
is.ObjectOf(child)({ b: "a" }); // false
is.ObjectOf(child)({ a: 0, b: "a" }); // true
```

## Additional

`isStrictOf()` does not support this behavior.

```typescript
is.StrictOf(is.ObjectOf(child))({ a: 0, b: "a" }); // false
```

## Version
v4.0.1 7d8bcbd

**Comment by lambdalisue** [comment]
No, this is undefined behavior. I haven't considered the use of `is.ObjectOf` with `Object.create`.

Are you encountering a specific issue? Since `Object.create` returns `any`, the usage you've shown doesn't seem typical.

**Comment by Milly** [comment]
I am concerned that prototype pollution may result in behavior that developers do not intend.
In other words, if this behavior is not what you intended, I consider it a bug.

**Comment by Milly** [comment]
If to fix, the implementation should use `Object.keys()` instead of `for ... in`.
